//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBrewLabs.Parserly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevBrewLabs.Parserly.Resources.ParserMessages", typeof(ParserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atleast {0} count{1}.
        /// </summary>
        internal static string AtleastCount {
            get {
                return ResourceManager.GetString("AtleastCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atleast 1 parser match.
        /// </summary>
        internal static string AtleastOneParserMatch {
            get {
                return ResourceManager.GetString("AtleastOneParserMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atmost {0} count{1}.
        /// </summary>
        internal static string AtmostCount {
            get {
                return ResourceManager.GetString("AtmostCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-9.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of input.
        /// </summary>
        internal static string EndofInput {
            get {
                return ResourceManager.GetString("EndofInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} count{1}.
        /// </summary>
        internal static string GotCount {
            get {
                return ResourceManager.GetString("GotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position ({0}): Expected &apos;{1}&apos;.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a-z/A-Z.
        /// </summary>
        internal static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 parser match.
        /// </summary>
        internal static string NoParserMatch {
            get {
                return ResourceManager.GetString("NoParserMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string TypeConvertError {
            get {
                return ResourceManager.GetString("TypeConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position ({0}): Unexpected input. Expected &apos;{1}&apos; but got &apos;{2}&apos;.
        /// </summary>
        internal static string UnexpectedInputError {
            get {
                return ResourceManager.GetString("UnexpectedInputError", resourceCulture);
            }
        }
    }
}
